//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2.1.1-4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.18 at 01:26:54 PM CET 
//


package nl.rug.search.opr.entities;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for indicator.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="indicator">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="verynegative"/>
 *     &lt;enumeration value="negative"/>
 *     &lt;enumeration value="neutral"/>
 *     &lt;enumeration value="positive"/>
 *     &lt;enumeration value="verypositive"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "indicator")
@XmlEnum
public enum Indicator {

    @XmlEnumValue("verynegative")
    VERYNEGATIVE("verynegative"),
    @XmlEnumValue("negative")
    NEGATIVE("negative"),
    @XmlEnumValue("neutral")
    NEUTRAL("neutral"),
    @XmlEnumValue("positive")
    POSITIVE("positive"),
    @XmlEnumValue("verypositive")
    VERYPOSITIVE("verypositive");
    private final String value;

    Indicator(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Indicator fromValue(String v) {
        for (Indicator c: Indicator.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
