//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2.1.1-4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.18 at 01:26:54 PM CET 
//


package nl.rug.search.opr.entities;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PROBLEM"/>
 *     &lt;enumeration value="CONTEXT"/>
 *     &lt;enumeration value="SOLUTION"/>
 *     &lt;enumeration value="DESCRIPTION"/>
 *     &lt;enumeration value="FORCES"/>
 *     &lt;enumeration value="CONSEQUENCES"/>
 *     &lt;enumeration value="RELATIONSHIP"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "type")
@XmlEnum
public enum Type {

    PROBLEM,
    CONTEXT,
    SOLUTION,
    DESCRIPTION,
    FORCES,
    CONSEQUENCES,
    RELATIONSHIP;

    public String value() {
        return name();
    }

    public static Type fromValue(String v) {
        return valueOf(v);
    }

}
