//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2.1.1-4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.18 at 01:26:54 PM CET 
//


package nl.rug.search.opr.entities;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final QName _Pattern_QNAME = new QName("", "pattern");
    private final QName _ResultList_QNAME = new QName("", "resultList");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FileDTO }
     * 
     */
    public FileDTO createFileDTO() {
        return new FileDTO();
    }

    /**
     * Create an instance of {@link License }
     * 
     */
    public License createLicense() {
        return new License();
    }

    /**
     * Create an instance of {@link QualityAttribute }
     * 
     */
    public QualityAttribute createQualityAttribute() {
        return new QualityAttribute();
    }

    /**
     * Create an instance of {@link ResultList }
     * 
     */
    public ResultList createResultList() {
        return new ResultList();
    }

    /**
     * Create an instance of {@link Force }
     * 
     */
    public Force createForce() {
        return new Force();
    }

    /**
     * Create an instance of {@link Consequence }
     * 
     */
    public Consequence createConsequence() {
        return new Consequence();
    }

    /**
     * Create an instance of {@link RelationshipDTO }
     * 
     */
    public RelationshipDTO createRelationshipDTO() {
        return new RelationshipDTO();
    }

    /**
     * Create an instance of {@link Content }
     * 
     */
    public Content createContent() {
        return new Content();
    }

    /**
     * Create an instance of {@link ArrayList }
     * 
     */
    public ArrayList createArrayList() {
        return new ArrayList();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link PatternDTO }
     * 
     */
    public PatternDTO createPatternDTO() {
        return new PatternDTO();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PatternDTO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pattern")
    public JAXBElement<PatternDTO> createPattern(PatternDTO value) {
        return new JAXBElement<PatternDTO>(_Pattern_QNAME, PatternDTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResultList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "resultList")
    public JAXBElement<ResultList> createResultList(ResultList value) {
        return new JAXBElement<ResultList>(_ResultList_QNAME, ResultList.class, null, value);
    }

}
