% This project documentation was generated through the TeX export of the
%                        Open Decision Repository
%             http://code.google.com/p/opendecisionrepository/

\documentclass{article}
\usepackage{textcomp}

\author{$project.name$ contributors}
\title{$project.name$}

\begin{document}
    \maketitle
    \clearpage
    \tableofcontents

    \input{description}
    \input{members}
    \input{iterations}
    \input{concerns}
    \input{decisions}
\end{document}